# Generated by Django 4.0.6 on 2022-07-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='fecha_nacimineto',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='año',
            new_name='anyo',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(),
        ),
    ]
